// TouchType analytics dashboard: lightweight SVG charts over local learning data.
window.KQ = window.KQ || {};
KQ.analytics = (() => {
  const esc=s=>KQ.escapeHtml(String(s??''));
  const svgNS='http://www.w3.org/2000/svg';
  const fmtDate=d=>new Date(d).toLocaleDateString([], {month:'short',day:'numeric'});
  const clamp=(v,a,b)=>Math.max(a,Math.min(b,v));
  function data(profile,days){const cutoff=days==='all'?0:Date.now()-Number(days)*86400000;return (profile.drillRecords||[]).filter(d=>new Date(d.date).getTime()>=cutoff&&['adaptive','lesson','weak','test'].includes(d.mode)).slice().reverse()}
  function svg(root,h=250){root.innerHTML='';const s=document.createElementNS(svgNS,'svg');s.setAttribute('viewBox','0 0 800 '+h);s.classList.add('analytics-svg');root.appendChild(s);return s}
  function line(s,x1,y1,x2,y2,cls='chart-grid'){const e=document.createElementNS(svgNS,'line');for(const [k,v] of Object.entries({x1,y1,x2,y2}))e.setAttribute(k,v);e.setAttribute('class',cls);s.appendChild(e)}
  function label(s,x,y,t,anchor='start'){const e=document.createElementNS(svgNS,'text');e.setAttribute('x',x);e.setAttribute('y',y);e.setAttribute('text-anchor',anchor);e.setAttribute('class','chart-label');e.textContent=t;s.appendChild(e)}
  function lineChart(root,rows,specs,min=0,max=null){const s=svg(root),W=800,H=250,L=52,R=18,T=18,B=36;max=max??Math.max(1,...rows.flatMap(r=>specs.map(q=>Number(r[q.key])||0)));for(let i=0;i<=4;i++){const y=T+(H-T-B)*i/4,v=Math.round(max-(max-min)*i/4);line(s,L,y,W-R,y);label(s,L-8,y+4,v,'end')}if(!rows.length){label(s,W/2,H/2,'No data yet','middle');return}const X=i=>rows.length===1?(L+W-R)/2:L+(W-L-R)*i/(rows.length-1),Y=v=>T+(H-T-B)*(1-(clamp(v,min,max)-min)/(max-min||1));specs.forEach((q,si)=>{const p=document.createElementNS(svgNS,'path');p.setAttribute('d',rows.map((r,i)=>(i?'L':'M')+X(i)+' '+Y(Number(r[q.key])||0)).join(' '));p.setAttribute('class','chart-series series-'+si);p.setAttribute('fill','none');s.appendChild(p);rows.forEach((r,i)=>{const c=document.createElementNS(svgNS,'circle');c.setAttribute('cx',X(i));c.setAttribute('cy',Y(Number(r[q.key])||0));c.setAttribute('r',4);c.setAttribute('class','chart-point series-'+si);const tt=document.createElementNS(svgNS,'title');tt.textContent=fmtDate(r.date)+' · '+q.label+': '+r[q.key]+(q.suffix||'');c.appendChild(tt);s.appendChild(c)})});const n=Math.min(5,rows.length);for(let i=0;i<n;i++){const idx=Math.round((rows.length-1)*(n===1?0:i/(n-1)));label(s,X(idx),H-10,fmtDate(rows[idx].date),'middle')}}
  function barChart(root,rows,key,suffix=''){const s=svg(root,280),W=800,H=280,L=48,R=16,T=18,B=42;if(!rows.length){label(s,W/2,H/2,'No key data yet','middle');return}const max=Math.max(1,...rows.map(r=>Number(r[key])||0)),gap=5,bw=(W-L-R-gap*(rows.length-1))/rows.length;rows.forEach((r,i)=>{const v=Number(r[key])||0,h=(H-T-B)*(v/max),x=L+i*(bw+gap),y=H-B-h,rect=document.createElementNS(svgNS,'rect');for(const [k,val] of Object.entries({x,y,width:bw,height:h,rx:4}))rect.setAttribute(k,val);rect.setAttribute('class','chart-bar');const tt=document.createElementNS(svgNS,'title');tt.textContent=r.label+': '+Math.round(v)+suffix;rect.appendChild(tt);s.appendChild(rect);label(s,x+bw/2,H-18,r.label,'middle')});line(s,L,H-B,W-R,H-B,'chart-axis')}
  function keyRows(p){return Object.entries(p.keyStats||{}).filter(([k,s])=>k!==' '&&s.attempts).map(([k,s])=>({label:k.toUpperCase(),attempts:s.attempts,accuracy:100*(s.attempts-s.errors)/s.attempts,latency:s.samples?s.totalLatencyMs/s.samples:0,hesitation:s.samples?100*(s.slow||0)/s.samples:0})).sort((a,b)=>a.label.localeCompare(b.label))}
  function wordRows(p){const now=Date.now();return Object.entries(p.wordSkills||{}).map(([word,s])=>({word,stage:s.stage||0,retention:Math.round((s.retention||0)*100),stability:Number(s.stabilityDays||0),interval:Number(s.lastIntervalDays||0),due:s.due||0,dueNow:(s.due||0)<=now,errorRate:s.attempts?Math.round(100*(s.errors||0)/s.attempts):0})).sort((a,b)=>(a.dueNow===b.dueNow?0:a.dueNow?-1:1)||a.due-b.due)}
  function render(profile,days=30){const drills=data(profile,days),adaptive=drills.filter(d=>d.mode==='adaptive'),keys=keyRows(profile),words=wordRows(profile),quality=drills.filter(d=>d.timingSamples).map(d=>({date:d.date,accuracy:d.accuracy||0,hesitation:d.hesitation||0}));lineChart(document.getElementById('chart-speed'),drills.map(d=>({date:d.date,wpm:d.wpm||0})),[{key:'wpm',label:'WPM'}],0);lineChart(document.getElementById('chart-quality'),quality,[{key:'accuracy',label:'Accuracy',suffix:'%'},{key:'hesitation',label:'Hesitation',suffix:'%'}],0,100);barChart(document.getElementById('chart-keys'),keys,'accuracy','%');const total=drills.length,avgWpm=total?Math.round(drills.reduce((a,d)=>a+(d.wpm||0),0)/total):0,avgAcc=total?Math.round(drills.reduce((a,d)=>a+(d.accuracy||0),0)/total):0,avgHes=quality.length?Math.round(quality.reduce((a,d)=>a+d.hesitation,0)/quality.length):0,fluent=words.filter(w=>w.stage>=2).length;document.getElementById('analytics-summary').innerHTML=[[total,'Drills'],[avgWpm,'Avg WPM'],[avgAcc+'%','Avg accuracy'],[avgHes+'%','Avg hesitation'],[fluent,'Fluent words'],[words.filter(w=>w.dueNow).length,'Due now']].map(x=>'<div class="stat"><span class="stat-val">'+x[0]+'</span><span class="stat-label">'+x[1]+'</span></div>').join('');document.getElementById('analytics-keys-table').innerHTML='<tr><th>Key</th><th>Attempts</th><th>Accuracy</th><th>Avg latency</th><th>Hesitation</th></tr>'+(keys.length?keys.map(k=>'<tr><td><strong>'+esc(k.label)+'</strong></td><td>'+k.attempts+'</td><td>'+Math.round(k.accuracy)+'%</td><td>'+Math.round(k.latency)+' ms</td><td>'+Math.round(k.hesitation)+'%</td></tr>').join(''):'<tr><td colspan="5" class="muted">No key data yet.</td></tr>');document.getElementById('analytics-words-table').innerHTML='<tr><th>Word</th><th>State</th><th>Retention</th><th>Stability</th><th>Last interval</th><th>Next review</th><th>Error rate</th></tr>'+(words.length?words.slice(0,100).map(w=>'<tr><td><strong>'+esc(w.word)+'</strong></td><td>'+(w.stage>=2?'Fluent':'Learning')+'</td><td>'+(w.retention?w.retention+'%':'–')+'</td><td>'+(w.stability?w.stability.toFixed(1)+' d':'–')+'</td><td>'+(w.interval?w.interval.toFixed(1)+' d':'–')+'</td><td>'+(w.dueNow?'Due now':fmtDate(w.due))+'</td><td>'+w.errorRate+'%</td></tr>').join(''):'<tr><td colspan="7" class="muted">No word data yet.</td></tr>');document.getElementById('analytics-caption').textContent=adaptive.length+' adaptive drill'+(adaptive.length===1?'':'s')+' in this range · scheduler: '+((profile.settings?.srsMode||'adaptive')==='ladder'?'Classic ladder':'Adaptive motor SRS')}
  return {render};
})();
